#!/bin/sh

# This finds objects that the pre-merge script moved out of the way to
# avoid conflicts when running git clone and moves them back to their
# original places. The result is that the git repository gets checked out
# and the extant objects end up back in the working directory. Git now
# sees these as un-staged changes to the working branch and you can deal
# with them by adding them or reverting.

find -name '*.vcsh-unclobber' -execdir rename .vcsh-unclobber '' {} \;
